global:
  LANGUAGES:
    - - en
      - English
    - - pt-br
      - Portuguese (Brazil)
  MODELTRANSLATION_DEFAULT_LANGUAGE: pt-br
production:
  ALLOWED_HOSTS:
    - https://cv-maker-4btk.onrender.com
  DATABASES:
    default:
      ENGINE: django.db.backends.postgresql
      PORT: 5432
  DEBUG: false
  STORAGES:
    staticfiles:
      BACKEND: whitenoise.storage.CompressedManifestStaticFilesStorage
