global:
  LANGUAGES:
    - - en
      - English
    - - pt-br
      - Portuguese (Brazil)
  MODELTRANSLATION_DEFAULT_LANGUAGE: pt-br

development:
  DEBUG: true
  ALLOWED_HOSTS:
    - "*"

production:
  ALLOWED_HOSTS:
    - cv-maker-4btk.onrender.com
  DEBUG: false
  STORAGES:
    staticfiles:
      BACKEND: whitenoise.storage.CompressedManifestStaticFilesStorage
