# Generated by Django 4.2.4 on 2023-08-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_pt_br',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_pt_br',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='educationcourse',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='educationcourse',
            name='name_pt_br',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='educationdegree',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='educationdegree',
            name='name_pt_br',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='educationinstitution',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='educationinstitution',
            name='name_pt_br',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_pt_br',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='experiencerole',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='experiencerole',
            name='name_pt_br',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_pt_br',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_pt_br',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_pt_br',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='role',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='role',
            name='name_pt_br',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_pt_br',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='state',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='state',
            name='name_pt_br',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
    ]
