# Generated by Django 4.2.4 on 2023-08-16 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_city_name_en_city_name_pt_br_country_name_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userskill',
            options={'verbose_name': 'user skill', 'verbose_name_plural': 'user skills'},
        ),
        migrations.RemoveField(
            model_name='userskill',
            name='level',
        ),
    ]
