# Generated by Django 4.2.4 on 2023-08-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_city'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='education',
            name='unique_education',
        ),
        migrations.RemoveField(
            model_name='education',
            name='is_completed',
        ),
        migrations.AlterField(
            model_name='usersocialnetwork',
            name='username',
            field=models.CharField(max_length=100, verbose_name='username'),
        ),
        migrations.AddConstraint(
            model_name='education',
            constraint=models.UniqueConstraint(fields=('user', 'institution', 'course', 'degree'), name='unique_education'),
        ),
        migrations.AddConstraint(
            model_name='usersocialnetwork',
            constraint=models.UniqueConstraint(fields=('username', 'social_network'), name='unique_username_social_network'),
        ),
    ]
