# Generated by Django 4.2.4 on 2023-08-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_education_unique_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationinstitution',
            name='acronym',
            field=models.CharField(default='UFV', max_length=10, verbose_name='acronym'),
            preserve_default=False,
        ),
    ]
