# Generated by Django 4.2.4 on 2023-08-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_educationinstitution_acronym'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetwork',
            name='suffix',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='suffix'),
        ),
    ]
