# Generated by Django 4.1.12 on 2023-11-09 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_socialnetwork_suffix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brief',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('brief', models.CharField(max_length=255, verbose_name='user brief')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'brief',
                'verbose_name_plural': 'briefs',
                'db_table': 'core_briefs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('brief', models.CharField(max_length=255, verbose_name='brief')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
                'db_table': 'core_companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('brief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.brief')),
                ('cv_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.cvlanguage')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.role')),
                ('skills', models.ManyToManyField(related_name='+', to='core.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cv',
                'verbose_name_plural': 'cvs',
                'db_table': 'core_cvs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='brief',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company'),
        ),
        migrations.AddField(
            model_name='brief',
            name='user_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.userrole'),
        ),
    ]
