global:
  LANGUAGES:
    - ["en", "English"]
    - ["pt-br", "Portuguese (Brazil)"]
  MODELTRANSLATION_DEFAULT_LANGUAGE: "pt-br"

production:
  STORAGES:
    staticfiles:
      BACKEND: whitenoise.storage.CompressedManifestStaticFilesStorage
  DATABASES:
    default:
      ENGINE: django.db.backends.postgresql
  DEBUG: False
  ALLOWED_HOSTS:
    - https://cv-maker-4btk.onrender.com
